### PR TITLE
remove unused values.yaml, switching to full jsonnet

### PR DESCRIPTION
**Pull request by prydonius**
Removes old configuration values, the new dashboard does not need any configuration.

### CODE REVIEW

**Comment by andresmgot** [comment]
@prydonius why is the CI all red?

**Comment by prydonius** [comment]
@andresmgot looks like the same reason it's been red for the other PRs, I could look into fixing it, but since we're planning on moving this repo to kubeapps/kubeapps I'm not sure it's worth it?

**Comment by prydonius** [comment]
The issue is that `./kubeapps.sh up` is failing because it's trying to create the AppRepository resource before the AppRepository CRD object is created. The order was fixed in a newer version of Kubecfg which is what I'm trying in #41.

This shouldn't happen when we move this to the kubeapps/kubeapps repo and test with the real kubeapps binary.

**Comment by andresmgot** [comment]
👍

**Review by andresmgot — APPROVED** [review]

**Pull request merged**
